-
  name: Flatline
  damage: 16
  headshot_damage: 32
  legshot_damage: 12
  rate_of_fire: 600
  ammo_capacity: 20
  tactical_reload: 2.4
  empty_reload: 3.1
  ammo_type: heavy
  projectile_speed: 26000
  draw_time: 0.6
  holster_time: 0.55
  available_attachments:
    magazine:
      - extended_heavy_mag
    optics:
      - 2x_hcog_bruiser
      - 1x_hcog_classic
      - 1x_holo
      - 1x-2x_variable_holo
      - 2x-4x_variable_aog
      - 3x_hcog_ranger
    stock:
      - standard_stock
  attachments_overwrite:
    extended_heavy_mag:
      rare:
        ammo_increase: 40%
      epic:
        ammo_increase: 50%
  fire_modes:
    single: true
    auto: true
  spray_pattern:
    starter:
      - x: 50
        y: 115
    follow:
      - x: -7
        y: -16
      - x: 4
        y: -4
      - x: -7
        y: -16
      - x: -4
        y: -4
      - x: -1
        y: -10
      - x: 1
        y: -8
      - x: 3
        y: -3
      - x: 6
        y: -4
      - x: 10
        y: 6
      - x: 2
        y: 2
      - x: -1
        y: 3
      - x: -2
        y: -2
      - x: -2
        y: -4
      - x: -15
        y: -3
      - x: -4
        y: -3
      - x: -2
        y: -8
      - x: -5
        y: -14
      - x: -5
        y: -4
-
  name: Hemlok
  damage: 18
  headshot_damage: 36
  legshot_damage: 13.5
  rate_of_fire: 490
  ammo_capacity: 18
  tactical_reload: 2.4
  empty_reload: 2.85
  ammo_type: heavy
  projectile_speed: 27500
  draw_time: 0.6
  holster_time: 0.55
  available_attachments:
    barrel:
      - barrel_stabilizer
      - flash_hider
    magazine:
      - extended_heavy_mag
    optics:
      - 2x_hcog_bruiser
      - 1x_hcog_classic
      - 1x_holo
      - 1x-2x_variable_holo
      - 2x-4x_variable_aog
      - 3x_hcog_ranger
    stock:
      - standard_stock
  attachments_overwrite:
    extended_heavy_mag:
      basic:
        ammo_increase: 33%
      epic:
        ammo_increase: 66%
  fire_modes:
    single: true
    burst: 3
  spray_pattern:
    starter:
      - x: 50
        y: 110
      - x: 47
        y: 93
      - x: 46
        y: 74
    follow:
      - x: -2
        y: -4
      - x: -3
        y: -17
      - x: -1
        y: -19
-
  name: R-301
  damage: 14
  headshot_damage: 28
  legshot_damage: 10.5
  rate_of_fire: 720
  ammo_capacity: 18
  tactical_reload: 2.4
  empty_reload: 3.2
  ammo_type: light
  projectile_speed: 29000
  draw_time: 0.6
  holster_time: 0.55
  available_attachments:
    barrel:
      - barrel_stabilizer
      - flash_hider
    magazine:
      - extended_light_mag
    optics:
      - 2x_hcog_bruiser
      - 1x_hcog_classic
      - 1x_holo
      - 1x-2x_variable_holo
      - 2x-4x_variable_aog
      - 3x_hcog_ranger
    stock:
      - standard_stock
  attachments_overwrite:
    extended_light_mag:
      basic:
        ammo_increase: 10%
      rare:
        ammo_increase: 40%
      epic:
        ammo_increase: 55%
  fire_modes:
    single: true
    auto: true
  spray_pattern:
    starter:
      - x: 45
        y: 125
    follow:
      - x: 3
        y: -11
      - x: -5
        y: -16
      - x: 6
        y: -12
      - x: 1
        y: -11
      - x: 5
        y: -16
      - x: 0
        y: -5
      - x: 2
        y: -7
      - x: 2
        y: -16
      - x: 5
        y: -4
      - x: 4
        y: 3
      - x: 2
        y: -7
      - x: 2
        y: -2
      - x: -5
        y: -3
      - x: -2
        y: -3
      - x: -8
        y: -2
      - x: -7
        y: -1
-
  name: Havoc
  damage: 18
  headshot_damage: 36
  legshot_damage: 13.5
  rate_of_fire: 672
  ammo_capacity: 32
  tactical_reload: 2.4
  empty_reload: 3.2
  ammo_type: energy
  projectile_speed: 30500
  draw_time: 0.5
  holster_time: 0.55
  available_attachments:
    optics:
      - 2x_hcog_bruiser
      - 1x_hcog_classic
      - 1x_holo
      - 1x-2x_variable_holo
      - 2x-4x_variable_aog
      - 3x_hcog_ranger
    hop_up:
      - selectfire_receiver
      - turbocharger
    stock:
      - standard_stock
  fire_modes:
    single: true
    auto: true
  spray_pattern:
    starter:
      - x: 45
        y: 125
    follow:
      - x: 3
        y: -8
      - x: -4
        y: -8
      - x: 2
        y: -6
      - x: -2
        y: -6
      - x: 2
        y: -6
      - x: 2
        y: -6
      - x: 2
        y: -6
      - x: 2
        y: -6
      - x: 0
        y: -6
      - x: -2
        y: -6
      - x: -2
        y: -6
      - x: -1
        y: -6
      - x: 0
        y: -6
      - x: 2
        y: -7
      - x: 2
        y: -5
      - x: 2
        y: -4
      - x: -2
        y: -3
      - x: -2
        y: -3
      - x: -2
        y: -3
      - x: -2
        y: -2
      - x: -1
        y: -1
      - x: 0
        y: -1
      - x: 0
        y: -1
