-
  name: Flatline
  damage: 16
  headshot_damage: 32
  legshot_damage: 12
  rate_of_fire: 600
  ammo_capacity: 20
  tactical_reload: 2.4
  empty_reload: 3.1
  ammo_type: heavy
  projectile_speed: 26000
  draw_time: 0.6
  holster_time: 0.55
  available_attachments:
    magazine:
      - extended_heavy_mag
    optics:
      - 2x_hcog_bruiser
      - 1x_hcog_classic
      - 1x_holo
      - 1x-2x_variable_holo
      - 2x-4x_variable_aog
      - 3x_hcog_ranger
    stock:
      - standard_stock
  fire_modes:
    single: true
    auto: true
-
  name: Hemlok
  damage: 18
  headshot_damage: 36
  legshot_damage: 13.5
  rate_of_fire: 490
  ammo_capacity: 18
  tactical_reload: 2.4
  empty_reload: 2.85
  ammo_type: heavy
  projectile_speed: 27500
  draw_time: 0.6
  holster_time: 0.55
  available_attachments:
    barrel:
      - barrel_stabilizer
      - flash_hider
    magazine:
      - extended_heavy_mag
    optics:
      - 2x_hcog_bruiser
      - 1x_hcog_classic
      - 1x_holo
      - 1x-2x_variable_holo
      - 2x-4x_variable_aog
      - 3x_hcog_ranger
    stock:
      - standard_stock
  fire_modes:
    single: true
    burst: 3
-
  name: R-301
  damage: 14
  headshot_damage: 28
  legshot_damage: 10.5
  rate_of_fire: 720
  ammo_capacity: 18
  tactical_reload: 2.4
  empty_reload: 3.2
  ammo_type: light
  projectile_speed: 29000
  draw_time: 0.6
  holster_time: 0.55
  available_attachments:
    barrel:
      - barrel_stabilizer
      - flash_hider
    magazine:
      - extended_light_mag
    optics:
      - 2x_hcog_bruiser
      - 1x_hcog_classic
      - 1x_holo
      - 1x-2x_variable_holo
      - 2x-4x_variable_aog
      - 3x_hcog_ranger
    stock:
      - standard_stock
  fire_modes:
    single: true
    auto: true
-
  name: Havoc
  damage: 18
  headshot_damage: 36
  legshot_damage: 13.5
  rate_of_fire: 672
  ammo_capacity: 25
  tactical_reload: 2.4
  empty_reload: 3.2
  ammo_type: energy
  projectile_speed: 30500
  draw_time: 0.5
  holster_time: 0.55
  available_attachments:
    optics:
      - 2x_hcog_bruiser
      - 1x_hcog_classic
      - 1x_holo
      - 1x-2x_variable_holo
      - 2x-4x_variable_aog
      - 3x_hcog_ranger
    hop_up:
      - selectfire_receiver
      - turbocharger
    stock:
      - standard_stock
  fire_modes:
    single: true
    auto: true
