-
  name: Flatline
  damage: 5
  clip_size: 18
  available_attachments:
    optic: true
    stock: true
    hop_up: false
    magazine: true
    barrel: true
-
  name: Hemlok
  damage: 4
  clip_size: 16
-
  name: R-301
  damage: 3
  clip_size: 19
