-
  name: Sniper Stock
  type: stock
  basic:
    description: Improves handling and reduces aim drift.
    draw_time: -15%
    holster_time: -15%
    lower_time: -10%
    ads: -30%
    zoom_time: -10%
  rare:
    description: Quicker handling & moderate aim drift reduction.
    draw_time: -20%
    holster_time: -20%
    lower_time: -15%
    ads: -50%
    zoom_time: -15%
  epic:
    description: Fast handling & large aim drift reduction.
    draw_time: -25%
    holster_time: -25%
    lower_time: -20%
    ads: -80%
    zoom_time: -20%
-
  name: Standard Stock
  type: stock
  basic:
    description: Improves handling and reduces aim drift.
    draw_time: -15%
    holster_time: -15%
    lower_time: -10%
    ads: -15%
    zoom_time: -15%
  rare:
    description: Quicker handling & moderate aim drift reduction.
    draw_time: -20%
    holster_time: -20%
    lower_time: -15%
    ads: -25%
    zoom_time: -20%
  epic:
    description: Fast handling & large aim drift reduction.
    draw_time: -25%
    holster_time: -25%
    lower_time: -20%
    ads: -40%
    zoom_time: -25%
-
  name: Shotgun Bolt
  type: stock
  basic:
    description: Small upgrade to fire rate
    fire_rate: 15%
    rechamber_time: -10%
  rare:
    description: Moderate upgrade to fire rate
    fire_rate: 25%
    rechamber_time: -20%
  epic:
    description: Maximum upgrade to fire rate
    fire_rate: 35%
    rechamber_time: -25%
-
  name: Barrel Stabilizer
  type: barrel
  basic:
    description: Small recoil reduction.
    kick_pitch_base: -5%
    kick_pitch_random: -20%
    kick_yaw_base: -5%
    kick_yaw_random: -10%
  rare:
    description: Moderate recoil reduction.
    kick_pitch_base: -10%
    kick_pitch_random: -25%
    kick_yaw_base: -10%
    kick_yaw_random: -15%
  epic:
    description: Large recoil reduction.
    kick_pitch_base: -15%
    kick_pitch_random: -30%
    kick_yaw_base: -15%
    kick_yaw_random: -20%
  legendary:
    description: Minimizes muzzle flash. Large recoil reduction.
    kick_pitch_base: -15%
    kick_pitch_random: -30%
    kick_yaw_base: -15%
    kick_yaw_random: -20%
-
  name: Precision Choke
  type: hop-up
  epic:
    description: Reduces projectile spread for compatible weapons.
    charge_levels: 4
    charge_time: 1.5
-
  name: Hammerpoint Rounds
  type: hop-up
  epic:
    description: Increased damage to unshielded targets.
    damage_modifier:
      Mozambique: 51%
      P2020: 162%
-
  name: Anvil Receiver
  type: hop-up
  legendary:
    description: Empowers semi-auto mode.
    damage_modifier:
      Flatline: 125%
      R-301: 150%
-
  name: Selectfire Receiver
  type: hop-up
  epic:
    description: Enables fire select for compatible weapons.
-
  name: Double Tap Trigger
  type: hop-up
  epic:
    description: Makes each trigger pull fire a quick two round burst.
-
  name: Turbocharger
  type: hop-up
  legendary:
    description: Reduces autofire spin-up time for compatible weapons.
-
  name: Extended Heavy Mag
  type: magazine
  note: Magazine increasements vary per weapon. These are the general rules.
  basic:
    description: Slightly increases ammo capacity.
    ammo_increase: 25%
  rare:
    description: Increased ammo capacity with quicker reloads.
    reload_time: -8%
    ammo_increase: 50%
  epic:
    description: High ammo capacity with fast reloads.
    reload_time: -13%
    ammo_increase: 100%
-
  name: Extended Light Mag
  type: magazine
  note: Magazine increasements vary per weapon. These are the general rules.
  basic:
    description: Slightly increases ammo capacity.
    ammo_increase: 25%
  rare:
    description: Increased ammo capacity with quicker reloads.
    reload_time: -8%
    ammo_increase: 50%
  epic:
    description: High ammo capacity with fast reloads.
    reload_time: -13%
    ammo_increase: 100%
-
  name: Extended Energy Mag
  type: magazine
  note: Magazine increasements vary per weapon. These are the general rules.
  basic:
    description: Slightly increases ammo capacity.
    ammo_increase: 20%
  rare:
    description: Increased ammo capacity with quicker reloads.
    reload_time: -8%
    ammo_increase: 40%
  epic:
    description: High ammo capacity with fast reloads.
    reload_time: -50%
    ammo_increase: 100%
-
  name: 1x HCOG 'CLASSIC'
  type: optic
  basic:
    description: Close range optic.
-
  name: 1x HOLO
  type: optic
  basic:
    description: Close range optic.
-
  name: 2x HCOG 'BRUISER'
  type: optic
  rare:
    description: Close range optic.
-
  name: 1x-2x VARIABLE HOLO
  type: optic
  rare:
    description: Close range optic with variable zoom.
-
  name: 6x SNIPER
  type: optic
  rare:
    description: Basic sniper optic.
-
  name: 2x-4x VARIABLE AOG
  type: optic
  epic:
    description: Mid-range optic with variable zoom.
-
  name: 3x HCOG 'RANGER'
  type: optic
  epic:
    description: Mid-range optic.
-
  name: 4x-8x VARIABLE SNIPER
  type: optic
  epic:
    description: Sniper optic with multiple zoom levels.
-
  name: 1x DIGITAL THREAT
  type: optic
  legendary:
    description: Close range optic with threat highlighting.
-
  name: 4x-10x DIGITAL SNIPER THREAT
  type: optic
  legendary:
    description: Sniper optic with threat highlighting and digital zoom.
