-
  name: Sniper Stock
  type: stock
  common:
    description: Improves handling and reduces aim drift.
    draw_time: -15%
    holster_time: -15%
    lower_time: -10%
    ads: -30%
    zoom_time: -10%
  rare:
    description: Quicker handling & moderate aim drift reduction.
    draw_time: -20%
    holster_time: -20%
    lower_time: -15%
    ads: -50%
    zoom_time: -15%
  epic:
    description: Fast handling & large aim drift reduction.
    draw_time: -25%
    holster_time: -25%
    lower_time: -20%
    ads: -80%
    zoom_time: -20%
-
  name: Standard Stock
  type: stock
  common:
    description: Improves handling and reduces aim drift.
    draw_time: -15%
    holster_time: -15%
    lower_time: -10%
    ads: -15%
    zoom_time: -15%
  rare:
    description: Quicker handling & moderate aim drift reduction.
    draw_time: -20%
    holster_time: -20%
    lower_time: -15%
    ads: -25%
    zoom_time: -20%
  epic:
    description: Fast handling & large aim drift reduction.
    draw_time: -25%
    holster_time: -25%
    lower_time: -20%
    ads: -40%
    zoom_time: -25%
-
  name: Shotgun Bolt
  type: shotgun_belt
  common:
    description: Small upgrade to fire rate
    fire_rate: 115%
    rechamber_time: -10%
  rare:
    description: Moderate upgrade to fire rate
    fire_rate: 125%
    rechamber_time: -20%
  epic:
    description: Maximum upgrade to fire rate
    fire_rate: 135%
    rechamber_time: -25%
-
  name: Barrel Stabilizer
  type: barrel
  common:
    description: Small recoil reduction.
    kick_pitch_base: -5%
    kick_pitch_random: -20%
    kick_yaw_base: -5%
    -10%
  rare:
    description: Moderate recoil reduction.
    kick_pitch_base: -10%
    kick_pitch_random: -25%
    kick_yaw_base: -10%
    -15%
  epic:
    description: Large recoil reduction.
    kick_pitch_base: -15%
    kick_pitch_random: -30%
    kick_yaw_base: -15%
    kick_yaw_random: -20%
-
  name: Flash Hider
  type: barrel
  legendary:
    description: Minimizes muzzle flash.
    kick_pitch_base: -15%
    kick_pitch_random: -30%
    kick_yaw_random: -15%
    kick_yaw_random: -20%
-
  name: Precision Choke
  type: hop-up
  epic:
    description: Reduces projectile spread for compatible weapons.
    charge_levels: 4
    charge_time: 1.5
-
  name: Selectfire receiver
  type: hop-up
  epic:
    description: Enables fire select for compatible weapons.
-
  name: Skullpiercer Rifling
  type: hop-up
  epic:
    description: Increased headshot damage for compatible weapons.
    damage_multiplier: 2.5
-
  name: Extended Heavy Mag
  type: magazine
  common:
    description: Slightly increases ammo capacity.
  rare:
    description: Increased ammo capacity with quicker reloads.
    reload_time: -8%
  epic:
    description: High ammo capacity with fast reloads.
    reload_time: -13%
-
  name: Extended Light Mag
  type: magazine
  common:
    description: Slightly increases ammo capacity.
  rare:
    description: Increased ammo capacity with quicker reloads.
    reload_time: -8%
  epic:
    description: High ammo capacity with fast reloads.
    reload_time: -13%
-
  name: 2x HCOG 'BRUISER'
  type: optic
  rare:
    description: Close range optic.
-
  name: 1x HCOG 'CLASSIC'
  type: optic
  common:
    description: Close range optic.
-
  name: 1x HOLO
  type: optic
  common:
    description: Close range optic.
-
  name: 1x-2x VARIABLE HOLO
  type: optic
  rare:
  description: Close range optic with variable zoom.
-
  name: 1x DIGITAL THREAT
  type: optic
  legendary:
    description: Close range optic with threat highlighting.
-
  name: 2x-4x VARIABLE AOG
  type: optic
  epic:
    description: Mid-range optic with variable zoom.
-
  name: 3x HCOG 'RANGER'
  type: optic
  epic:
    description: Mid-range optic.
-
  name: 6x SNIPER
  type: optic
  rare:
    description: Basic sniper optic.
-
  name: 4x-8x VARIABLE SNIPER
  type: optic
  epic:
    description: Sniper optic with multiple zoom levels.
-
  name: 4x-10x DIGITAL SNIPER THREAT
  type: optic
  legendary:
    description: Sniper optic with threat highlighting and digital zoom.
