-
  name: Helmet
  basic: <strong>10%</strong> Total Headshot Damage reduction
  rare: <strong>20%</strong> Total Headshot Damage reduction
  epic: <strong>25%</strong> Total Headshot Damage reduction
  legendary: <strong>25%</strong> Total Headshot Damage reduction. <br><br> Reduces Tactical and Ultimate <strong>Ability cooldowns</strong>.
-
  name: Body Shield
  basic: Absorbs <strong>50</strong> Damage
  rare: Absorbs <strong>75</strong> Damage
  epic: Absorbs <strong>100</strong> Damage
  legendary: <strong>6</strong> Extra inventory slots. <br><br> Healing and Shielding consumables take <Strong>half the time</strong> to use.
-
  name: Knockdown Shield
  basic: Blocks <strong>100</strong> Damage
  rare: Blocks <strong>250</strong> Damage
  epic: Blocks <strong>750</strong> Damage
  legendary: Blocks <strong>750</strong> Damage. <br><br> <strong>Self-Resurrect</strong> when downed (1 time use).<br><br>Self-revive takes <strong>12 seconds</strong> to use.
-
  name: Backpack
  basic: <strong>2</strong> Extra Inventory Slots
  rare: <strong>4</strong> Extra Inventory Slots
  epic: <strong>6</strong> Extra Inventory Slots
  legendary: Revive downed teammates with bonus health and shields (if they have armor).
