-
  name: Frag Grenade
  description: A throwable impact grenade that <strong>deals less damage the further you are</strong> from the explosion.
  impact_damage: 10
  explosion_damage: 100
  explosion_timer: 4
-
  name: Thermite Grenade
  description: A throwable item that leaves a line of fire which <strong>burns</strong> the enemy over a <strong>short period</strong> of time.
  impact_damage: 0
  explosion_damage: 0
  burn_damage: 4
  explosion_timer: On Impact
  effect_timer: 8
  after_burn_timer: 2
  ticks_per_second: 10
-
  name: Arc Star
  description: A throwable shuriken that <strong>sticks</strong> on impact and <strong>damages</strong> and <strong>stuns</strong> the enemy when it explodes. The impact damage is higher when sticking it to a enemy with a shield.
  impact_damage: 15
  explosion_damage: 70
  explosion_timer: 3
  effect_timer: 5
  impact_damage_vs_shields: 60
