-
  name: Bangalore
  abilities:
    ability_1:
      type: Tactical Ability
      name: Smoke Launcher
      description: Fire a high-velocity smoke canister that explodes into a smoke wall on impact.
      secondary_data:
        damage: 10
        duration: 20<small>s</small>
        radius: 7.5<small>m</small>
        cooldown: 33<small>s</small>
        charges: 2
    ability_2:
      type: Passive Ability
      name: Double Time
      description: Taking fire while sprinting makes you move faster for a brief time.
      secondary_data:
        movement: +25<small>%</small>
        duration: 2<small>s</small>
    ability_3:
      type: Ultimate Ability
      name: Rolling Thunder
      description: Call in an artillery strike that slowly creeps across the landscape.
      secondary_data:
        damage: 40
        charge_time: 270<small>s</small>
        radius: 25<small>m</small>
        slow: -35<small>%</small>
        detonation_time: 8<small>s</small>
        duration: 5<small>s</small>
-
  name: Bloodhound
  abilities:
    ability_1:
      type: Tactical Ability
      name: Eye of the Allfather
      description: Briefly reveal hidden enemies, traps, and clues throughout structures in front of you.
      secondary_data:
        cone: 125<small>deg</small>
        scan_range: 35<small>m</small>
        reveal_time: 1.5<small>s</small>
        cooldown: 35<small>s</small>
    ability_2:
      type: Passive Ability
      name: Tracker
      description: See tracks left behind by your foes.
      secondary_data:
        duration: 90<small>sec</small>
    ability_3:
      type: Ultimate Ability
      name: Beast of the Hunt
      description: Enhances your senses, allowing you move faster and highlighting your prey.
      secondary_data:
        movement: +30<small>%</small>
        charge_time: 180<small>s</small>
        duration: 35<small>s</small>
-
  name: Caustic
  abilities:
    ability_1:
      type: Tactical Ability
      name: Nox Gas Trap
      description: Drop canisters that release deadly Nox gas when shot or triggered by enemies.
      secondary_data:
        damage: 4 / 10<small>tick</small>
        gas_radius: 5<small>m</small>
        duration: 12.5<small>s</small>
        speed: -25<small>%</small>
        detection: 2.5<small>m</small>
        traps: 3
        max_traps_on_field: 6
        cooldown: 30<small>s</small>
    ability_2:
      type: Passive Ability
      name: Nox Vision
      description: Allows you to see enemies through your gas.
      extra: <h5>Fortified</h5> Reduces damage taken by 15%
    ability_3:
      type: Ultimate Ability
      name: Nox Gas Grenade
      description: Blankets a large area in Nox gas. Damage increases the longer an enemy is inside of it.
      secondary_data:
        damage: 1 / 10<small>tick</small>
        gas_radius: 10<small>m</small>
        duration: 20<small>s</small>
        speed: -25<small>%</small>
        throw_distance: 33<small>m</small>
        charge_time: 150<small>s</small>
-
  name: Gibraltar
  abilities:
    ability_1:
      type: Tactical Ability
      name: Dome of Protection
      description: Throw down a dome-shield that blocks attacks for 15 seconds. Players inside of the dome heal faster.
      secondary_data:
        radius: 5<small>m</small>
        duration: 18<small>s</small>
        throw_distance: 24<small>m</small>
        cooldown: 30<small>s</small>
        healing_speed_increase: 25<small>%</small>
    ability_2:
      type: Passive Ability
      name: Gun Shield
      description: Aiming down sights deploys a gun shield that blocks incoming fire.
      secondary_data:
        shield: 75
      extra: <h5>Fortified</h5> Reduces damage taken by 15%
    ability_3:
      type: Ultimate Ability
      name: Defensive Bombardment
      description: Call in a concentrated mortar strike on a marked position.
      secondary_data:
        damage: 40
        duration: 6<small>s</small>
        delay: 2<small>s</small>
        stun: 4<small>s</small>
        radius: 25<small>m</small>
        throw_range: 68<small>m</small>
        charge_time: 180<small>s</small>
-
  name: Lifeline
  about:
    real_name: Ajay Che
    age: 24
  abilities:
    ability_1:
      type: Tactical Ability
      name: D.O.C. Heal Drone
      description: Call your Drone of Compassion to automatically heal nearby teammates over time.
      secondary_data:
        cast_time: 2<small>s</small>
        cooldown: 60<small>s</small>
        healing_per_second: 5
        max_healing_range: 2<small>m</small>
        duration: 20<small>s</small>
    ability_2:
      type: Passive Ability
      name: Combat Medic
      description: Revive knocked down teammates faster while protected by a shield wall. Healing items are used 25% faster.
      extra: <h5>Low Profile</h5> Increases damage taken by 5%
      secondary_data:
        revive: 4<small>s</small>
        self_heal: -25<small>%</small>
    ability_3:
      type: Ultimate Ability
      name: Care Package
      description: Call in a drop pod full of high-quality defensive gear.
      secondary_data:
        items: 3
        cast_time: 15<small>s</small>
        charge_time: 360<small>s</small>
-
  name: Mirage
  abilities:
    ability_1:
      type: Tactical Ability
      name: Psyche Out
      description: Send out a holographic decoy to confuse the enemy.
      secondary_data:
        cooldown: 15<small>s</small>
        duration: 15<small>s</small>
    ability_2:
      type: Passive Ability
      name: Encore!
      description: Automatically drop a decoy and cloak for five seconds when knocked down.
      secondary_data:
        invisible_duration: 5<small>s</small>
    ability_3:
      type: Ultimate Ability
      name: Vanishing Act
      description: Deploy a team of Decoys to distract enemies while you cloak.
      secondary_data:
        duration: 5<small>s</small>
        decoys: 5
        invisible: 5<small>s</small>
        charge_time: 150<small>s</small>
-
  name: Pathfinder
  abilities:
    ability_1:
      type: Tactical Ability
      name: Grappling Hook
      description: Grapple to get to out-of-reach places quickly.
      secondary_data:
        range: 20<small>m</small>
        cooldown: 15<small>s</small>
    ability_2:
      type: Passive Ability
      name: Insider Knowledge
      description: Scan a survey beacon to reveal the ring’s next location.
      extra: <h5>Low Profile</h5> Increases damage taken by 5%
      secondary_data:
        cast_time: 8<small>s</small>
    ability_3:
      type: Ultimate Ability
      name: Zipline Gun
      description: Create a zipline for everyone to use.
      secondary_data:
        range: 135<small>m</small>
        max_speed_zipline: +200<small>%</small>
        charge_time: 120<small>s</small>
-
  name: Wraith
  abilities:
    ability_1:
      type: Tactical Ability
      name: Into the Void
      description: Reposition quickly through the safety of void space, avoiding all damage.
      secondary_data:
        movement: +10<small>%</small>
        duration: 3<small>s</small>
        cooldown: 20<small>s</small>
    ability_2:
      type: Passive Ability
      name: Voices from the Void
      description: A voice warns you when danger approaches. As far as you can tell, it’s on your side.
      extra: <h5>Low Profile</h5> Increases damage taken by 5%
      secondary_data:
        cooldown: 10<small>s</small>
        warn_teammates: +6<small>s</small>
    ability_3:
      type: Ultimate Ability
      name: Dimensional Rift
      description: Link two locations with portals for 60 seconds, allowing your entire team to use them.
      secondary_data:
        duration: 60<small>s</small>
        movement: +110<small>%</small>
        charge_time: 150<small>s</small>
-
  name: Octane
  abilities:
    ability_1:
      type: Tactical Ability
      name: Stim
      description: Move 30% faster for six seconds. Costs health to use.
      secondary_data:
        movement: +30<small>%</small>
        health_cost: 10<small>%</small>
    ability_2:
      type: Passive Ability
      name: Swift Mend
      description: Automatically restores health over time.
      secondary_data:
        healing: 0.5 <small>/sec</small>
        cooldown: 5 <small>sec</small>
    ability_3:
      type: Ultimate Ability
      name: Launch Pad
      description: Deploy a jump pad that catapults teammates through the air.
      secondary_data:
        charge_time: 90<small>s</small>
-
  name: Wattson
  abilities:
    ability_1:
      type: Tactical Ability
      name: Perimeter Security
      description: Connect nodes to create electrified fences that damage and slow enemies.
      secondary_data:
        damage: 10
        duration: 3 <small>sec</small>
    ability_2:
      type: Passive Ability
      name: Spark of Genius
      description: Ultimate Accelerants fully charge your Ultimate Ability, and standing near interception pylons boosts your Tactical Ability recharge.
      extra: <h5>Low Profile</h5> Increases damage taken by 5%
    ability_3:
      type: Ultimate Ability
      name: Interception Pylon
      description: Place an electrified pylon that destroys incoming ordnance and repairs damaged shields as long as it stands.
      secondary_data:
        max_pylons: 1
-
  name: Crypto
  abilities:
    ability_1:
      type: Tactical Ability
      name: Surveillance Drone
      description: Deploy an aerial camera drone. 40 second cooldown if destroyed.
      secondary_data:
        max_range: 200 <small>m</small>
        cooldown: 40 <small>s</small>
        activation_time: 2 <small>s</small>
    ability_2:
      type: Passive Ability
      name: Neurolink
      description: Crypto and his teammates see what his Surveillance Drone detects up to a 30m distance.
      secondary_data:
        max_scan_range: 30 <small>m</small>
    ability_3:
      type: Ultimate Ability
      name: Drone EMP
      description: Charge up an EMP from your drone. The blast deals 50 shield damage, slows players, and destroys traps.
      secondary_data:
        range: 20 <small>m</small>
        damage: 50
        slow_percentage: 75 <small>%</small>
        slow_duration: 3 <small>s</small>
