-
  name: Spitfire
  damage: 20
  headshot_damage: 40
  legshot_damage: 15
  rate_of_fire: 512
  ammo_capacity: 35
  tactical_reload: 2.8
  empty_reload: 3.33
  ammo_type: heavy
  projectile_speed: 27500
  draw_time: 0.7
  holster_time: 0.65
  available_attachments:
    barrel: true
    magazine: true
    hop_up: false
    optic: true
    stock: true
  fire_modes:
    auto: true
-
  name: Devotion
  damage: 17
  headshot_damage: 34
  legshot_damage: 12.75
  rate_of_fire: 900
  ammo_capacity: 44
  tactical_reload: 2.8
  empty_reload: 3.63
  ammo_type: energy
  projectile_speed: 33500
  draw_time: 0.7
  holster_time: 0.65
  available_attachments:
    barrel: true
    magazine: false
    hop_up: true
    optic: true
    stock: true
  fire_modes:
    auto: true
