-
  name: Spitfire
  damage: 18
  headshot_damage: 40
  legshot_damage: 15
  rate_of_fire: 512
  ammo_capacity: 35
  tactical_reload: 2.8
  empty_reload: 3.33
  ammo_type: heavy
  projectile_speed: 27500
  draw_time: 0.7
  holster_time: 0.65
  available_attachments:
    barrel:
      - barrel_stabilizer
      - flash_hider
    magezine:
      - extended_heavy_mag
    optics:
      - 1x_hcog_classic
      - 1x_holo
      - 2x_hcog_bruiser
      - 1x-2x_variable_holo
      - 2x-4x_variable_aog
      - 3x_hcog_ranger
    stock:
      - standard_stock
  attachments_overwrite:
    extended_heavy_mag:
      basic:
        ammo_increase: 14.28%
      rare:
        ammo_increase: 28.585%
      epic:
        ammo_increase: 57.155%
  fire_modes:
    auto: true
  spray_pattern:
    starter:
      - x: 85
        y: 120
    follow:
      - x: -5
        y: -15
      - x: -4
        y: -5
      - x: -8
        y: -10
      - x: -7
        y: -6
      - x: -5
        y: -7
      - x: 2
        y: -7
      - x: 3
        y: -2
      - x: 6
        y: 1
      - x: 2
        y: 4
      - x: 3
        y: -3
      - x: 1
        y: -6
      - x: -5
        y: -1
      - x: -10
        y: -2
      - x: -2
        y: -3
      - x: -10
        y: 2
      - x: -5
        y: 0
      - x: -3
        y: -6
      - x: -4
        y: -6
      - x: -6
        y: -5
      - x: -8
        y: -2
      - x: -4
        y: 1
      - x: 3
        y: -4
      - x: 4
        y: -3
      - x: 4
        y: -3
      - x: 4
        y: -3
      - x: 5
        y: -3
      - x: 4
        y: -3
      - x: -6
        y: 0
      - x: 5
        y: -5
      - x: 10
        y: 3
      - x: 3
        y: 2
      - x: 4
        y: -2
      - x: 2
        y: -6
-
  name: Devotion
  damage: 17
  headshot_damage: 34
  legshot_damage: 12.75
  rate_of_fire: 900
  ammo_capacity: 44
  tactical_reload: 2.8
  empty_reload: 3.63
  ammo_type: energy
  projectile_speed: 33500
  draw_time: 0.7
  holster_time: 0.65
  available_attachments:
    barrel:
      - barrel_stabilizer
      - flash_hider
    optics:
      - 1x_hcog_classic
      - 1x_holo
      - 2x_hcog_bruiser
      - 1x-2x_variable_holo
      - 2x-4x_variable_aog
      - 3x_hcog_ranger
    hop_up:
      - turbocharger
    stock:
      - standard_stock
  fire_modes:
    auto: true
  spray_pattern:
    starter:
      - x: 75
        y: 125
    follow:
      - x: 4
        y: -20
      - x: 3
        y: -13
      - x: -3
        y: -10
      - x: -4
        y: -7
      - x: -5
        y: -6
      - x: -3
        y: -8
      - x: -8
        y: -5
      - x: -5
        y: -5
      - x: -3
        y: -5
      - x: -7
        y: -7
      - x: -4
        y: -4
      - x: -5
        y: -1
      - x: -5
        y: -5
      - x: -5
        y: 0
      - x: -3
        y: 1
      - x: -4
        y: -2
      - x: 4
        y: -5
      - x: 2
        y: -4
      - x: 6
        y: -5
      - x: 3
        y: -2
      - x: 3
        y: -2
      - x: 5
        y: 0
      - x: -4
        y: -4
