-
  name: RE-45
  damage: 11
  headshot_damage: 16.5
  legshot_damage: 9.9
  rate_of_fire: 750
  ammo_capacity: 15
  tactical_reload: 1.74
  empty_reload: 2.12
  ammo_type: light
  projectile_speed: 488
  draw_time: 0.35
  holster_time: 0.3
  available_attachments:
    barrel:
      - barrel_stabilizer
      - flash_hider
    magazine:
      - extended_light_mag
    optics:
      - 1x_hcog_classic
      - 1x_holo
      - 2x_hcog_bruiser
      - 1x-2x_variable_holo
      - 1x_digital_threat
  attachments_overwrite:
    extended_light_mag:
      basic:
        ammo_increase: 20%
      rare:
        ammo_increase: 40%
      epic:
        ammo_increase: 60%
  fire_modes:
    auto: true
  spray_pattern:
    starter:
      - x: 25
        y: 100
    follow:
      - x: 4
        y: -6
      - x: 4
        y: -6
      - x: 8
        y: -6
      - x: 4
        y: -6
      - x: 4
        y: -6
      - x: 3
        y: -4
      - x: 6
        y: -5
      - x: 5
        y: -7
      - x: 3
        y: -1
      - x: 4
        y: -4
      - x: 1
        y: -5
      - x: -2
        y: -6
      - x: 8
        y: -2
      - x: 3
        y: -3
-
  name: P2020
  damage: 13
  headshot_damage: 19.5
  legshot_damage: 11.7
  rate_of_fire: 430
  ammo_capacity: 10
  tactical_reload: 1.25
  empty_reload: 1.25
  ammo_type: light
  projectile_speed: 462
  draw_time: 0.25
  holster_time: 0.2
  available_attachments:
    barrel:
      - barrel_stabilizer
      - flash_hider
    magazine:
      - extended_light_mag
    optics:
      - 1x_hcog_classic
      - 1x_holo
      - 2x_hcog_bruiser
      - 1x-2x_variable_holo
      - 1x_digital_threat
  attachments_overwrite:
    extended_light_mag:
      basic:
        ammo_increase: 30%
      rare:
        ammo_increase: 50%
      epic:
        ammo_increase: 80%
  fire_modes:
    single: true
-
  name: Wingman
  damage: 45
  headshot_damage: 90
  legshot_damage: 40.5
  rate_of_fire: 156
  ammo_capacity: 4
  tactical_reload: 2.1
  empty_reload: 2.1
  ammo_type: heavy
  projectile_speed: 450
  draw_time: 0.45
  holster_time: 0.4
  available_attachments:
    barrel:
      - barrel_stabilizer
      - flash_hider
    magazine:
      - extended_heavy_mag
    hop_up:
      - skullpiercer_rifling
    optics:
      - 1x_hcog_classic
      - 1x_holo
      - 2x_hcog_bruiser
      - 1x-2x_variable_holo
      - 1x_digital_threat
  attachments_overwrite:
    skullpiercer_rifling:
      epic:
        headshot_damage_modifier: 25%
    extended_heavy_mag:
      basic:
        ammo_increase: 50%
      rare:
        ammo_increase: 100%
      epic:
        ammo_increase: 150%
  fire_modes:
    single: true
