-
  name: Mozambique
  damage: 15
  damage_modifier: 3
  headshot_damage: 22.5
  legshot_damage: 12
  rate_of_fire: 180
  ammo_capacity: 3
  tactical_reload: 2.1
  empty_reload: 2.6
  ammo_type: shotgun
  projectile_speed: 10000
  draw_time: 0.45
  holster_time: 0.4
  available_attachments:
    optics:
      - 2x_hcog_bruiser
      - 1x_hcog_classic
      - 1x_holo
      - 1x-2x_variable_holo
      - 1x_digital_threat
    stock:
      - shotgun_bolt
  fire_modes:
    auto: true
  spray_pattern:
    starter:
      - x: 30
        y: 80
      - x: 70
        y: 80
      - x: 50
        y: 50
-
  name: Peacekeeper
  damage: 10
  damage_modifier: 11
  headshot_damage: 15
  legshot_damage: 8
  rate_of_fire: 58
  ammo_capacity: 6
  tactical_reload: 2.5
  empty_reload: 3.5
  ammo_type: shotgun
  projectile_speed: 16000
  draw_time: 0.45
  holster_time: 0.4
  available_attachments:
    hop_up:
      - precision_choke
    optics:
      - 2x_hcog_bruiser
      - 1x_hcog_classic
      - 1x_holo
      - 1x-2x_variable_holo
      - 1x_digital_threat
    stock:
      - shotgun_bolt
  fire_modes:
    single: true
-
  name: EVA-8 Auto
  damage: 7
  damage_modifier: 9
  headshot_damage: 10.5
  legshot_damage: 5.6
  rate_of_fire: 128
  ammo_capacity: 8
  tactical_reload: 2.75
  empty_reload: 3.0
  ammo_type: shotgun
  projectile_speed: 16000
  draw_time: 0.45
  holster_time: 0.4
  available_attachments:
    optics:
      - 2x_hcog_bruiser
      - 1x_hcog_classic
      - 1x_holo
      - 1x-2x_variable_holo
      - 1x_digital_threat
    stock:
      - shotgun_bolt
  fire_modes:
    auto: true
-
  name: Mastiff
  damage: 18
  damage_modifier: 8
  headshot_damage: 36
  legshot_damage: 18
  rate_of_fire: 96
  ammo_capacity: 4
  tactical_reload: 1.03
  empty_reload: n/a
  ammo_type: unique
  projectile_speed: 12000
  draw_time: 0.8
  holster_time: 0.4
  fire_modes:
    single: true
