-
  name: G7 Scout
  damage: 30
  headshot_damage: 60
  legshot_damage: 21.75
  rate_of_fire: 4.5
  ammo_capacity: 10
  tactical_reload: 2.4
  empty_reload: 3.0
  ammo_type: light
  projectile_speed: 31500
  draw_time: 0.9
  holster_time: 0.6
  available_attachments:
    optic: true
    stock: true
    hop_up: false
    magazine: true
    barrel: true
-
  name: Longbow
  damage: 55
  headshot_damage: 110
  legshot_damage: 39.88
  rate_of_fire: 1.2
  ammo_capacity: 5
  tactical_reload: 2.66
  empty_reload: 3.66
  ammo_type: heavy
  projectile_speed: 30500
  draw_time: 0.9
  holster_time: 0.6
  available_attachments:
    optic: true
    stock: true
    hop_up: false
    magazine: true
    barrel: true
-
  name: Triple Take
  damage: 30
  headshot_damage: 60
  legshot_damage: 21.75
  rate_of_fire: 1.25
  ammo_capacity: 5
  tactical_reload: 2.6
  empty_reload: 3.4
  ammo_type: energy
  projectile_speed: 32000
  draw_time: 0.9
  holster_time: 0.6
  available_attachments:
    optic: true
    stock: true
    hop_up: false
    magazine: true
    barrel: true
-
  name: Kraber
  damage: 125
  headshot_damage: 250
  legshot_damage: 95
  rate_of_fire: 0
  ammo_capacity: 4
  tactical_reload: 3.2
  empty_reload: 4.3
  ammo_type: unique
  projectile_speed: 29500
  draw_time: 1.2
  holster_time: 0.7
  available_attachments:
    optic: true
    stock: true
    hop_up: false
    magazine: true
    barrel: true
