-
  name: G7 Scout
  damage: 34
  headshot_damage: 60
  legshot_damage: 27
  rate_of_fire: 273
  ammo_capacity: 10
  tactical_reload: 2.4
  empty_reload: 3.0
  ammo_type: light
  projectile_speed: 788
  draw_time: 0.9
  holster_time: 0.6
  available_attachments:
    barrel:
      - barrel_stabilizer
      - flash_hider
    magazine:
      - extended_light_mag
    optics:
      - 1x_hcog_classic
      - 1x_holo
      - 2x_hcog_bruiser
      - 1x-2x_variable_holo
      - 2x-4x_variable_aog
      - 3x_hcog_ranger
      - 6x_sniper
      - 4x-8x_variable_sniper
      - 4x-10x_digital_sniper_threat
    stock:
      - sniper_stock
    hop_up:
      - double_tap_trigger
  attachments_overwrite:
    extended_light_mag:
      basic:
        ammo_increase: 50%
      rare:
        ammo_increase: 80%
  fire_modes:
    single: true
-
  name: Longbow
  damage: 55
  headshot_damage: 110
  legshot_damage: 44
  rate_of_fire: 78
  ammo_capacity: 6
  tactical_reload: 2.66
  empty_reload: 3.66
  ammo_type: heavy
  projectile_speed: 763
  draw_time: 0.9
  holster_time: 0.6
  available_attachments:
    barrel:
      - barrel_stabilizer
      - flash_hider
    magazine:
      - extended_heavy_mag
    optics:
      - 1x_hcog_classic
      - 1x_holo
      - 2x_hcog_bruiser
      - 1x-2x_variable_holo
      - 2x-4x_variable_aog
      - 3x_hcog_ranger
      - 6x_sniper
      - 4x-8x_variable_sniper
      - 4x-10x_digital_sniper_threat
    stock:
      - sniper_stock
  fire_modes:
    single: true
-
  name: Triple Take
  damage: 23
  damage_modifier: 3
  headshot_damage: 46
  legshot_damage: 21
  rate_of_fire: 88
  ammo_capacity: 5
  tactical_reload: 2.6
  empty_reload: 3.4
  ammo_type: energy
  projectile_speed: 800
  draw_time: 0.9
  holster_time: 0.6
  available_attachments:
    magazine:
      - extended_energy_mag
    optics:
      - 1x_hcog_classic
      - 1x_holo
      - 2x_hcog_bruiser
      - 1x-2x_variable_holo
      - 2x-4x_variable_aog
      - 3x_hcog_ranger
      - 6x_sniper
      - 4x-8x_variable_sniper
      - 4x-10x_digital_sniper_threat
    hop_up:
      - precision_choke
    stock:
      - sniper_stock
  attachments_overwrite:
    extended_energy_mag:
      basic:
        ammo_increase: 20%
      rare:
        ammo_increase: 35%
      epic:
        ammo_increase: 50%
  fire_modes:
    single: true
  spray_pattern:
    starter:
      - x: 35
        y: 70
      - x: 50
        y: 70
      - x: 65
        y: 70
-
  name: Kraber
  damage: 145
  headshot_damage: 297.25
  legshot_damage: 110.2
  rate_of_fire: 36
  ammo_capacity: 4
  tactical_reload: 3.2
  empty_reload: 4.3
  ammo_type: unique
  projectile_speed: 738
  draw_time: 1.2
  holster_time: 0.7
  fire_modes:
    single: true
-
  name: Charge Rifle
  damage: 90
  rate_of_fire: 30
  ammo_capacity: 4
  headshot_damage: 121
  legshot_damage: 90
