-
  designation: Very strong
  description: This category contains weapons that are almost always too good not to bring with you. These weapons are strong enough that even in the hands of someone less skilled they will perform well.
  items:
    - name: kraber
      description: |
        <p>This legendary weapon has the potential to one-shot any enemy regardless of their armor, health, and helmet. For this reason alone it is a top pick. Of course this isn't easy, but even with simple body shots this weapon deals more damage than anything else in the game.</p>

        <p>It's largest downsides are it's slow fire rate and small amount of ammo, but most of all it's rarity. It can also be difficult to use effectively with a small circle or in close quarters, but in any other situations the Kraber is hard to beat.</p>
    - name: mastiff
      description: |
        <p>This legendary shotgun has the highest DPS of all shotguns. But raw statistics mean very little in the heat of battle. What makes this shotgun great is it's consistency. It's spread is very easy to work with, when hitting only part of the shots you will still deal a good amount of damage. It even has the potential to one-shot any enemy with a well placed headshot.</p>

        <p>It's biggest downsides are the same as the Kraber, it's rarity and it's limited ammo. Getting this early in the game might mean you run out of ammo and will need to find a new gun.</p>

        <p>In the hands of someone skilled it's hard to beat the Mastiff.</p>
    - name: peacekeeper
      description: |
        <p>Despite the recent nerfs the Peacekeeper remains a force to be reckoned with. It deals a large amount of damage at close range and has a large amount of attachments available to make it even stronger. With a Precision Choke it turns in to a solid medium range sniper along with it's regular capabilities. Whether it's early or late in the game, you can't go wrong with a Peacekeeper.</p>
-
  designation: Strong
  description: The weapons in this category are always a solid choice. Some of these require attachments to be truly effective, but they will be strong regardless.
  items:
    - name: havoc
      description: |
        <p>The Havoc is a real hit or miss. Some love it, some hate it. Most of this comes down to the wind up time, which can be difficult to get used to. Add a Turbocharger and this becomes a non-issue. Another option is the Selectfire Receiver, but this one again is a difficult one to get used to. It's beam is hitscan, unlike any other weapon in the game.</p>

        <p>The recent buffs have definitely increased it's power. It's high standard ammo capacity is unlike any other assault rifle. From the start it's a solid pick up, with the right attachments it can be a real monster.</p>

        <p>Once you do get a feel for this weapon it can be a real beast. It's low recoil, relatively high rate of fire, and high damage often come as a surprise.</p>
    - name: r-301
      description: |
        <p>Perhaps the most reliable and simple gun in the game. It has an exceptionally high rate of fire, it's recoil pattern is very predictable and it's very accurate at longer ranges.</p>

        <p>It's the most "regular" gun you will find, but there in lies it strengths. It does require some good attachments to really get going, but even without it is a reliable weapon.</p>
    - name: spitfire
      description: |
        <p>In Apex Legends many weapons share the same problem; their magazine size is rather small which means you will need to reload often. With an LMG like the Spitfire you do not have the problem and you can use this to your advantage. In constant fire you can put out is a real danger. In top of that is deals a ton of damage and has manageable recoil. Add some good attachments and the Spitfire becomes a real monster.</p>

        <p>The Spitfire is easy to use and very forgiving. If you are struggling to consitantly do well in Apex, consider giving the Spitfire a chance.</p>
    - name: r-99
      description: |
        <p>The R-99 has the highest rate of fire of all guns, by a significant margin. This allows you to melt enemies faster than with any other weapon. This also makes the weapon more difficult to use than others, as missing means you will have to reload more quickly and frequently than others.</p>

        <p>Add an Extended Light Magazine and see your enemies melt before your eyes as you pull the trigger.</p>
    - name: longbow
      description: |
        <p>A very classic Sniper that can take out enemies very quickly. It has enough damage potential to put pressure on your enemies as you shoot at them from far.</p>

        <p>It's biggest weakness is it's need for a proper Scope. On top of that it's not easy to use. It's slow rate of fire means you better hit your shots, or your enemies might escape before you can land a hit. But in the hands of a skilled sniper the Longbow will be a real force. The recent buffs have definitely upped it in power, but we will have to see how much it truly affects it.</p>
    - name: devotion
      description: |
        <p>The Devotion's biggest weakness used to be the rarity of Energy ammo. With the recent update to their spawnrate this has changed. The damage the Devotion can put out is unlike anything else. Add a Turbocharger and you will melt anything in your path. Even it's recoil pattern is easy enough to work with.</p>

        <p>It's biggest weakness is that Energy ammo only stacks up to 60, unlike all other ammo types which stack to 80. This means you will need more bagspace to carry enough ammo with you. It also cannot use an Extended Magazine. While it's capacity isn't bad, it's high rate of fire might mean you need to reload more often than you'd like with an LMG.</p>
-
  designation: Good
  description: The weapons in the category can be decent in the right hands, but either require a great skill, or an excessive amount of attachments.
  items:
    - name: wingman
      description: |
        <p>Despite the recent nerfs to the Wingman it remains a solid pick. It's magazine size is now significantly smaller, but it's still enough to kill an enemy with some well aimed shots. An extended mag is now definitely a necessity if you wish to carry it in to late game. Early game it remains a solid pick up, even without any attachments.</p>

        <p>Another strength of the Wingman is it's low ammo requirement. This keeps your backup free for all sorts of pick ups you might otherwise not want to carry around.</p>
    - name: hemlok
      description: |
        <p>Burst fire weapons can be difficult to use and are generally not well liked. Putting this in single fire mode can make it a strong weapon, but at that point a G7-Scout or Wingman might just serve you better.</p>
    - name: flatline
      description: |
        <p>The flatline is a fairly straight forward gun. Unfortunately it's low rate of fire and awful recoil pattern make this a difficult weapon to use. Other Assault Rifles do a better job and are more often than not a better choice.</p>
    - name: prowler
      description: |
        <p>The Prowler can put out a lot of damage and can be very strong. But only with the right attachments. It really needs the Selectfire Receiver and a good Extended Heavy Mag. Without it this weapon is difficult to use well.</p>
    - name: eva-8_auto
      description: |
        <p>This Shotgun can certainly be powerful, especially in the early game. It's high rate of fire make it easier to use than the Peacekeeper, but it's spread is more difficult to work with. All in all not a bad weapon, just outshined by others.</p>
    - name: g7_scout
      description: |
        <p>The G7 Scout is a difficult weapon to place. It can be very strong at mid range, but it's very difficult to do well with. It's not reliant on any attachments, but it's very high skill ceiling is what places this weapon in this category.</p>

        <p>It can be a strong choice, but often times an Assault Rifle will be a more reliable choice.</p>
    - name: triple_take
      description: |
        <p>The Triple take is the most forgiving sniper. It's spread means landing shots is easier. But at the same time it doesn't quite deal the same amount of damage as the Longbow.</p>
        <p>Add a Precision Choke and the Triple Take suddenly becomes a much stronger sniper, at the cost of rate of fire. It can deal a large amount of damage which certainly makes it a viable choice. Unfortunately it's lack of a Magazine attachment puts a real damper on it's power.</p>
-
  designation: Average
  description: These weapons will serve you well in a pinch, but are outclassed by most others.
  items:
    - name: alternator
      description: |
        <p>The Alternator is not a bad little gun. It's slow rate of fire and easy to manage recoil make it quite reliable. Unfortunate most larger guns simply outperform it.</p>
        <p>It will serve you well in the early game, but it's better off replaced as soon as you find something better.</p>
    - name: re-45
      description: |
        <p>It's high rate of fire and tiny recoil makes for some awesome burst damage. But just like the Alternator, it's better off replaced by something with a little more firepower. It's definitely not a bad pick up early on in the game.</p>
-
  designation: Below Average
  description: The weapons in this category are better than nothing, but you should seek to replace them as soon as possible.
  items:
    - name: p2020
      description: |
        <p>Better than nothing, but not by much. It's low rate of fire, low damage, and lack of meaningful attachments puts the P2020 far below others.</p>
-
  designation: Weak
  description: These weapons are not good enough to compete. They are outclassed by anything else, and you might not even consider picking them up even if you have nothing else.
  items:
    - name: mozambique
      description: |
        <p>The Mozambique has far too low damage output, has a tiny magazine size, and can't carry any meaningful attachments. If you're in a situation where the Mozambique is all you have, you're better off using Melee.</p>
